### ISSUE TITLE
CA Cert injection is broken

### ISSUE THREAD

**Issue by joeljeske** [coder/enterprise-helm#111]
From 1.18.1 -> 1.19.1, CA Cert injection is broken. Our BitBucket Git OAuth provider is using self signed TLS CA. Now when trying to link an account, there is a TLS CA error. Skimming the YAML here it looks like the CA Bundle got dropped from being mounted in #59

**Comment by jawnsy** [comment]
Whew, I'm very sorry for the long delay in getting back to you! Thank you for your patience and the report. I believe the certificate mounting issue should be fixed in https://github.com/cdr/enterprise-helm/pull/102 -- I will double check this, but if you have any feedback on whether the issue has been fixed, that would be great to know!

**Comment by ericpaulsen** [comment]
Closed via #102.
